### ISSUE TITLE
Any plans on a prompt with text input? 

### ISSUE THREAD

**Issue by caph1993** [flexxui/dialite#3]
Just wondering if there are any plans on a prompt for asking the user for a string, or a password. An example of what I mean is the [Message Box module](https://pyautogui.readthedocs.io/en/latest/msgbox.html?highlight=message) of the pyAutoGUI library.

**Comment by almarklein** [comment]
Good question, that would be really useful indeed!

We use different native systems on Linux/Windows/OS to pop up a simple dialog. Therefore we need to work with what's possible at the intersection of these methods, and IIRC asking a user string is not possible on all platforms.
